force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>MRID-{0000}</displayFormat>
        <label>Maintenance Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>PMID-{0000}</displayFormat>
        <label>Property Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Maintenance_Requests_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Requests_Assigned__c</fullName>
    <label>Maintenance Requests Assigned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaintenenceRequestTriggerHandlerTest.cls
@isTest
public class MaintenenceRequestTriggerHandlerTest {
    @isTest
    public static void testvendorAssign(){
        List<vendor__c> vList= new List<vendor__c>();
        for (Integer i=1; i<=5; i++){
            vList.add(new vendor__c(Name='Test'+i, Email__c='krishnanshreeya@gmail.com', Maintenance_Requests_Assigned__c=i));
        }
        insert vList;
        Property__c prop= new Property__c(Property_Name__c='Test Property ', Type__c='Residential', status__c='Available', 
            rent__c= 13000, description__c='hi', address__CountryCode__s='IN',
            address__StateCode__s='TN', address__city__s='Chennai', address__PostalCode__s='600001'); 
        insert prop;
        List<Maintenance_Request__c> maintenanceList= new List<Maintenance_Request__c>();
        for (Integer i=1; i<=5; i++){
            maintenanceList.add(new Maintenance_Request__c(Property__c=prop.id, status__c= 'Completed'));
    	}
        List<AggregateResult> aggResult = [Select Vendor__c, COUNT(Id) ReqCount from Maintenance_Request__c
                                           where Vendor__c != null group by Vendor__c order by COUNT(Id) Desc limit 1];
		if (!aggResult.isEmpty()) {
            Integer cnt = Integer.valueOf(aggResult[0].get('ReqCount'));
            Assert.areEqual(5, cnt, 'The minimum workload count should be 5');
        }
	}
}