force-app/main/default/objects/Lease_Agreement__c/Lease_Agreement__c.object-meta.xml
<CustomObject>
    <label>Lease Agreement</label>
    <nameField>
        <displayFormat>LID-{0000}</displayFormat>
        <label>Lease Agreement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lease_Agreement__c/fields/Agreed_monthly_rent__c.field-meta.xml
<CustomField>
    <fullName>Agreed_monthly_rent__c</fullName>
    <label>Agreed monthly rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lease_Agreement__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lease Agreements</relationshipLabel>
    <relationshipName>Lease_Agreements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>PMID-{0000}</displayFormat>
        <label>Property Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Rent__c.field-meta.xml
<CustomField>
    <fullName>Rent__c</fullName>
    <label>Rent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupied</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tenant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeaseAgreementEmailingTest.cls
@isTest
public class LeaseAgreementEmailingTest {
    @TestSetup
    public static void loadData(){
        List<Contact> conList= new List<contact>();
        List<Property__c> propList= new List<Property__c>();
        List<lease_Agreement__c> leaseList= new List<lease_agreement__c>();
        contact ca= new contact(FirstName='ababa', lastName='bababa', email='krishnanshreeya@gmail.com');
        insert ca;
        for (integer i=1; i<=3; i++){
            conList.add(new contact(FirstName='Test', lastName='Name'+i, email='krishnanshreeya@gmail.com'));
            propList.add(new Property__c(Property_Name__c='Test Property '+i, Type__c='Residential', status__c='Occupied', 
            rent__c= 13000, description__c='hi', address__CountryCode__s='IN', tenant__c=ca.id,
            address__StateCode__s='TN', address__city__s='Chennai', address__PostalCode__s='600001'));
        }
        insert conList;
        insert propList;
        contact c= [Select id from contact limit 1];
        property__c p= [Select id from property__c limit 1];
        for (integer i=1; i<=3; i++){
            if (i==1 || i==2){
                 leaseList.add(new lease_Agreement__c(agreed_monthly_rent__c=15000, 
                                                     end_date__c= Date.today().addmonths(1), tenant__c=c.Id,
                                                     property__c=p.Id));
            }
            else{
                leaseList.add(new lease_Agreement__c(agreed_monthly_rent__c=16000, 
                                                     end_date__c= Date.today().addmonths(3), tenant__c=c.Id,
                                                     property__c=p.Id));
            }
        }
        insert leaseList;
    }
    @isTest
    public static void Testbatch(){
        Test.startTest();
        Database.ExecuteBatch(new LeaseAgreementEmailing(),10);
        Test.stopTest();
        List<EmailMessage> e=[Select subject from EmailMessage where subject='Lease Agreement about to expire'];
        assert.areEqual(2, e.size(),'Error');
    }
}